### ISSUE TITLE
No encoding specified when writing, Windows issue using self generated files

### ISSUE THREAD

**Issue by JanDeneweth-bmx** [sourmash-bio/sourmash#1428]
I am working on Windows 10 with Sourmash 3.5.0 (you may know me from issue [1318]( https://github.com/dib-lab/sourmash/issues/1318)). However, based on the code the issue should still occur v4.0.

**Please don't mind me being vague on details for now, I will clarify this issue when my colleague is back from Easter break!**

When creating concatenated files (I think!) and subsequently using them on Windows, differences in file encoding cause incompatibilities (or errors) to occur. This is because Python's `open` in python 3 uses the system encoding by default when writing in text mode, while (I think the issue is) writing JSON files always writes UTF-8 encoded data to a file opened in binary mode. Unlike in Linux, the default encoding may not be UTF-8 on Windows. 

From the [docs](https://docs.python.org/3.7/library/functions.html#open):

> _encoding_ is the name of the encoding used to decode or encode the file. This should only be used in text mode. The default encoding is platform dependent (whatever locale.getpreferredencoding() returns), but any text encoding supported by Python can be used. See the codecs module for the list of supported encodings.

This is very regrettable since it often causes bugs and confusion, and it may take several more releases before Python changes this behaviour. A [warning](https://www.python.org/dev/peps/pep-0597/) for such change in the future may be introduced in 3.10.

This bug may be solved by specifying the encoding to UTF-8 in every `open`. I will admit, I'm not sure what other issues this may bring. But given the presumably small userbase on windows, it's better to change this sooner rather than later, requiring all inputs to be UTF-8 while ensuring all outputs are UTF-8 and thus compatible with further calls to sourmash.

**Comment by ctb** [comment]
thanks, got it! straightforward to fix & thanks for pointing it out :)

**Comment by JanDeneweth-bmx** [comment]
Reproduction steps after syncing with my colleague:

1. I create a fasta file named "é.fasta" (é is not part of the 7-bit ASCII character set)
2. I use compute to generate a *.sig file which has in its contents "é.fasta" but using the system default ASCII + codepage ([cp1252](https://en.wikipedia.org/wiki/Windows-1252) on our systems). The é is basically written as byte "\xe9".

```
[
  {
     "class": "sourmash_signature",
     "email": "",
     "hash_function": "0.murmur64",
     "filename": "\xe9.fasta",
     "license": "CC0",
     "signatures": [
        ...
     ],
     "version": 0.4
  }
 ]
```

3. We pass this file to sourmash "cat", which fails

```
 "C:\Program Files\...\sourmash_<OurProgramAbbrev>.exe" sig cat é.fasta.sig > all.sig
  
  == This is sourmash version 3.5.0. ==
  == Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==
  
  Error while reading signatures from 'é.fasta.sig'.
  (continuing)
  Traceback (most recent call last):
    File "sourmash_bn.py", line 7, in <module>
      sys.exit(main())
    File "C:\Program Files\...\sourmash\__main__.py", line 13, in main
      return mainmethod(args)
    File "C:\Program Files\...\sourmash\cli\sig\cat.py", line 28, in main
      return sourmash.sig.__main__.cat(args)
    File "C:\Program Files\...\sourmash\sig\__main__.py", line 94, in cat
      notify('loaded {} signatures from {}...', n_loaded, sigfile, end='\r')
  UnboundLocalError: local variable 'n_loaded' referenced before assignment
  [10992] Failed to execute script sourmash_<OurProgramAbbrev>
```

As you can see in the following snippet, errors may occur from this conversion. In the context, it may get garbled to nonsense, or the error might be caught in a try-except but cause issues down the line.

```python
>>> val = b"\xe9"
>>> val.decode('cp1252')
'é'
>>> val.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: unexpected end of data
```

**Comment by ctb** [comment]
excellent, thank you!

Note for others, the specific error you're running into with `local variable referenced before assignment` is of course disconnected from this encoding issue; see https://github.com/dib-lab/sourmash/issues/1194.

**Comment by ctb** [comment]
This *might* have been fixed in #1493, and that will be part of sourmash v4.1. Leaving this open to wait for confirmation ;)

**Comment by ctb** [comment]
this is almost certainly fixed but would be good to add some unicode tests to make sure.
