### ISSUE TITLE
panic bug in `MinHash.seq_to_hashes`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1699]
I ran into a panic when working on doctests for #1695, but foolishly did not stop to save the exact code. I'm leaving it here so that @mr-eyes or I can return to it later to figure out what probably happened.

My guess is I provided too short a DNA sequence to  the method `seq_to_hashes` for a protein `MinHash`, but it's not trivial to replicate.

```
UNEXPECTED EXCEPTION: Panic()
Traceback (most recent call last):
  File "/Users/t/miniconda3/envs/py37/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)
  File "<doctest api-example.md[68]>", line 1, in <module>
  File "/Users/t/dev/sourmash/src/sourmash/minhash.py", line 346, in kmers_and_hashes
    bad_kmers_as_zeroes=bad_kmers_as_zeroes)
  File "/Users/t/dev/sourmash/src/sourmash/minhash.py", line 317, in seq_to_hashes  
    hashes_ptr = self._methodcall(lib.kmerminhash_seq_to_hashes, to_bytes(sequence), len(sequence), force, bad_kmers_as_zeroes, is_protein, size)
  File "/Users/t/dev/sourmash/src/sourmash/utils.py", line 25, in _methodcall
    return rustcall(func, self._get_objptr(), *args)
  File "/Users/t/dev/sourmash/src/sourmash/utils.py", line 78, in rustcall
    raise exc
sourmash.exceptions.Panic: sourmash panicked: thread 'unnamed' panicked with 'removal index (is 0) should be < len (is 0)' at library/alloc/src/vec/mod.rs:1385
/Users/t/dev/sourmash/doc/api-example.md:284: UnexpectedException
```

**Comment by mr-eyes** [comment]
This code will reproduce the error

```python
from sourmash import MinHash
mh = MinHash(0, 2, True, dayhoff=True, hp=False, scaled = 1)
print(mh.seq_to_hashes('ACGAT'))
```

I think this happened because "ACGAT" is 5nts-long and cannot be decoded into two amino acids, and 2 is the kmer-size. Will debug and fix.
