### ISSUE TITLE
panic bug in `sourmash sketch dna` with bad input and `--check-sequence`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1700]
saving here for later resolution - found while working on #1695.
```
% sourmash sketch dna short.fa -o short.fa.sig -p k=31,scaled=1 --check-sequence

== This is sourmash version 4.2.1.dev9+g02f2128. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

computing signatures for files: short.fa
Computing a total of 1 signature(s).
... reading sequences from short.fa
Traceback (most recent call last):
  File "/Users/t/miniconda3/envs/py37/bin/sourmash", line 33, in <module>
    sys.exit(load_entry_point('sourmash', 'console_scripts', 'sourmash')())
  File "/Users/t/dev/sourmash/src/sourmash/__main__.py", line 13, in main
    return mainmethod(args)
  File "/Users/t/dev/sourmash/src/sourmash/cli/sketch/dna.py", line 89, in main
    return sourmash.command_sketch.dna(args)
  File "/Users/t/dev/sourmash/src/sourmash/command_sketch.py", line 216, in dna
    _execute_sketch(args, signatures_factory)
  File "/Users/t/dev/sourmash/src/sourmash/command_sketch.py", line 196, in _execute_sketch
    _compute_individual(args, signatures_factory)
  File "/Users/t/dev/sourmash/src/sourmash/command_compute.py", line 194, in _compute_individual
    args.input_is_protein, args.check_sequence)
  File "/Users/t/dev/sourmash/src/sourmash/command_compute.py", line 256, in add_seq
    sig.add_sequence(seq, not check_sequence)
  File "/Users/t/dev/sourmash/src/sourmash/signature.py", line 154, in add_sequence
    self._methodcall(lib.signature_add_sequence, to_bytes(sequence), force)
  File "/Users/t/dev/sourmash/src/sourmash/utils.py", line 25, in _methodcall
    return rustcall(func, self._get_objptr(), *args)
  File "/Users/t/dev/sourmash/src/sourmash/utils.py", line 78, in rustcall
    raise exc
sourmash.exceptions.Panic: sourmash panicked: thread 'unnamed' panicked with 'called `Result::unwrap()` on an `Err` value: InvalidDNA { message: "NTCTGATCTCGGATAAACAAGCGATCCCAGT" }' at src/core/src/signature.rs:617
```

**Comment by mr-eyes** [comment]
Would you please upload the `short.fa`? not really important but would help.

**Comment by ctb** [comment]
it's in tests/test-data/short.fa

On Mon, Aug 02, 2021 at 02:57:26PM -0700, Mohamed Abuelanin wrote:
> Would you please upload the `short.fa`? not really important but would help.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sourmash-bio/sourmash/issues/1700#issuecomment-891360613
-- 
C. Titus Brown, ***@***.***

**Comment by mr-eyes** [comment]
This code will reproduce the bug:

```python
from sourmash import MinHash, signature

e = MinHash(n=1, ksize=21)
sig = signature.SourmashSignature(e)
sig.add_sequence("N" * 21)
```
