### ISSUE TITLE
Missing strain-level comma breaks `sourmash tax`

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash#1867]
I have a taxonomy file like this:

```
accession,taxid,superkingdom,phylum,class,order,family,genus,species,strain
RAOQ01000001.1,2306336,Eukaryota,Ascomycota,Sordariomycetes,Sordariales,Sordariaceae,Neurospora,Neurospora sp. FGSC 26626,
RAOP01000001.1,2306337,Eukaryota,Ascomycota,Sordariomycetes,Sordariales,Sordariaceae,Neurospora,Neurospora sp. FGSC 26627
```

Notice the missing strain-level trailing comma in the last line? well, this breaks the whole process with the following error:

```
== This is sourmash version 4.2.4. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

Traceback (most recent call last):
  File "/home/mhussien/miniconda3/envs/astrangia/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/mhussien/miniconda3/envs/astrangia/lib/python3.9/site-packages/sourmash/__main__.py", line 13, in main
    return mainmethod(args)
  File "/home/mhussien/miniconda3/envs/astrangia/lib/python3.9/site-packages/sourmash/cli/tax/annotate.py", line 67, in main
    return sourmash.tax.__main__.annotate(args)
  File "/home/mhussien/miniconda3/envs/astrangia/lib/python3.9/site-packages/sourmash/tax/__main__.py", line 267, in annotate
    tax_assign = MultiLineageDB.load(args.taxonomy_csv,
  File "/home/mhussien/miniconda3/envs/astrangia/lib/python3.9/site-packages/sourmash/tax/tax_utils.py", line 885, in load
    this_tax_assign = LineageDB.load(location, **kwargs)
  File "/home/mhussien/miniconda3/envs/astrangia/lib/python3.9/site-packages/sourmash/tax/tax_utils.py", line 597, in load
    lineage = [ (a, lca_utils.filter_null(b)) for (a,b) in lineage ]
  File "/home/mhussien/miniconda3/envs/astrangia/lib/python3.9/site-packages/sourmash/tax/tax_utils.py", line 597, in <listcomp>
    lineage = [ (a, lca_utils.filter_null(b)) for (a,b) in lineage ]
  File "/home/mhussien/miniconda3/envs/astrangia/lib/python3.9/site-packages/sourmash/lca/lca_utils.py", line 101, in <lambda>
    filter_null = lambda x: 'unassigned' if x.strip() in \
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by ctb** [comment]
thanks!

I think One Right Way to fix this is to substitute '' (empty string) when
there is a None in a lineage tuple name when loading taxonomies.

Alternatively or additionally, we could fix lca_utils.filter_null to
do this for us.
