### ISSUE TITLE
zlib error: files too large?

### ISSUE THREAD

**Issue by nmb85** [sourmash-bio/sourmash#2164]
Hi, we're (@deveshbhatnagar) having problems sketching large files (two 26 GB files in one case and two 39 GB files in another).

We run this:
`sourmash sketch dna -p 'k=21,k=31,k=51,scaled=1000,seed=42,abund' -o /datapool/results_235249040/d3gxy1ck105282021_S346.sig --merge /datapool/results_235249040/d3gxy1ck105282021_S346/meta_sample_1.fq.gz /datapool/results_235249040/d3gxy1ck105282021_S346/meta_sample_2.fq.gz`

We get this error output:

```
/datapool/results_235249040/d3gxy1ck105282021_S346/meta... /datapool/results_235249040/d3gxy1ck105282021_S346/meta_sample_2.fq.gz 162860000Traceback (most recent call last):
  File "/home/devesh/in_progress/venv/bin/sourmash", line 8, in <module>
    sys.exit(main())
  File "/home/devesh/in_progress/venv/lib/python3.9/site-packages/sourmash/__main__.py", line 13, in main
    return mainmethod(args)
  File "/home/devesh/in_progress/venv/lib/python3.9/site-packages/sourmash/cli/sketch/dna.py", line 90, in main
    return sourmash.command_sketch.dna(args)
  File "/home/devesh/in_progress/venv/lib/python3.9/site-packages/sourmash/command_sketch.py", line 239, in dna
    _execute_sketch(args, signatures_factory)
  File "/home/devesh/in_progress/venv/lib/python3.9/site-packages/sourmash/command_sketch.py", line 218, in _execute_sketch
    _compute_merged(args, signatures_factory)
  File "/home/devesh/in_progress/venv/lib/python3.9/site-packages/sourmash/command_compute.py", line 273, in _compute_merged
    for n, record in enumerate(screed.open(filename)):
  File "/home/devesh/in_progress/venv/lib/python3.9/site-packages/screed/fastq.py", line 57, in fastq_iter
    line = to_str(handle.readline().strip())
  File "/usr/lib/python3.9/gzip.py", line 398, in readline
    return self._buffer.readline(size)
  File "/usr/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.9/gzip.py", line 495, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid bit length repeat
```
Has anyone else had zlib errors?

**Comment by ctb** [comment]
hi, to me this looks like your files may be corrupt...!

you might try
```
gunzip -c FILENAME.gz | tail
```
just to see if gunzip also barfs.

it might be that implementations other than the internal python gzip library have better error handling, so to test that you can try streaming into `sourmash sketch`, e.g.
```
gunzip -c *.gz | sourmash sketch dna -p 'k=21,k=31,k=51,scaled=1000,seed=42,abund' -o /datapool/results_235249040/d3gxy1ck105282021_S346.sig -
```

**Comment by nmb85** [comment]
That was indeed the problem! The files were being corrupted by software upstream of sourmash sketch! Thanks for pointing that out. Closing.

**Comment by ctb** [comment]
excellent!
