### ISSUE TITLE
Panic Error when using sourmash gather

### ISSUE THREAD

**Issue by bryshalm** [sourmash-bio/sourmash#2616]
Attempted to run single command on command line with an srun of 25G on med2 and conda environment `sourmash_env` in directory `~brymoore/sourmash_16S/sample_k11_sig_files`

```!
sourmash gather SRR596245_V1_k11.sig ../silva/zipped_directory_sigs/SILVA_138_k11.fasta.sig.zip -o SRR596245_V1_k11.csv --threshold=0
```

**Output**
```!

== This is sourmash version 4.6.1. ==                                                                  == Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==
                                                                                                       select query k=11 automatically.                                                                       loaded query: SRR596245.1 GLKYXIS02GHTVR/2... (k=11, DNA)
Traceback (most recent call last):ctory_sigs/SILVA_138_k11.fasta.sig.zip'...
  File "/home/brymoore/miniconda3/envs/sourmash_env/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/__main__.py", line 13, in main
    return mainmethod(args)
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/cli/gather.py", line 158, in main
    return sourmash.commands.gather(args)
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/commands.py", line 725, in gather
    databases = sourmash_args.load_dbs_and_sigs(args.databases, query, False,
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/sourmash_args.py", line 308, in load_dbs_and_sigs
    db = _load_database(filename, False, cache_size=cache_size)
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/sourmash_args.py", line 458, in _load_database
    db = load_fn(filename,
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/sourmash_args.py", line 421, in _load_zipfile
    db = ZipFileLinearIndex.load(filename,
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/index/__init__.py", line 586, in load
    storage = ZipStorage(location)
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/sbt_storage.py", line 107, in __init__
    self._objptr = rustcall(lib.zipstorage_new, to_bytes(path), len(path))
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/utils.py", line 78, in rustcall
    raise exc
sourmash.exceptions.Panic: sourmash panicked: thread 'unnamed' panicked with 'called `Result::unwrap()` on an `Err` value: UnsupportedArchive("No support for multi-disk archives: disk (42454) != disk with central directory (35209)")' at src/core/src/storage.rs:255
```

The `SILVA_138_k11.fasta.sig.zip` is located in `~brymoore/sourmash_16S/silva/zipped_directory_sigs`
Command used to create the  zip file:
```
sourmash sig cat SILVA_138_k11.fasta.sig -o SILVA_138_k11.fasta.sig.zip
```

Used sig summarize  in directory `~brymoore/sourmash_16S/silva/zipped_directory_sigs`:
```
sourmash sig summarize SILVA_138_k11.fasta.sig.zip
``` 

**Output**
```
   == This is sourmash version 4.6.1. ==                                                                  == Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==
   ** loading from 'SILVA_138_k11.fasta.sig.zip'                                                          Traceback (most recent call last):                                                                       File "/home/brymoore/miniconda3/envs/sourmash_env/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/__main__.py", line 13, in main
    return mainmethod(args)
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/cli/sig/fileinfo.py", line 46, in main
    return sourmash.sig.__main__.fileinfo(args)
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/sig/__main__.py", line 1248, in fileinfo
    idx = sourmash_args.load_file_as_index(args.path,
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/sourmash_args.py", line 511, in load_file_as_index
    return _load_database(filename, yield_all_files)
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/sourmash_args.py", line 458, in _load_database
    db = load_fn(filename,
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/sourmash_args.py", line 421, in _load_zipfile
    db = ZipFileLinearIndex.load(filename,
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/index/__init__.py", line 586, in load
    storage = ZipStorage(location)
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/sbt_storage.py", line 107, in __init__
    self._objptr = rustcall(lib.zipstorage_new, to_bytes(path), len(path))
  File "/home/brymoore/miniconda3/envs/sourmash_env/lib/python3.10/site-packages/sourmash/utils.py", line 78, in rustcall
    raise exc
sourmash.exceptions.Panic: sourmash panicked: thread 'unnamed' panicked with 'called `Result::unwrap()` on an `Err` value: UnsupportedArchive("No support for multi-disk archives: disk (42454) != disk with central directory (35209)")' at src/core/src/storage.rs:255
```

Unfortunately, I have already deleted all of the unzipped SILVA sig files :( .

**Comment by ctb** [comment]
hi @bryshalm,

I tried running:
```
unzip -v SILVA_138_k11.fasta.sig.zip
```
and got:
```
Archive:  SILVA_138_k11.fasta.sig.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of SILVA_138_k11.fasta.sig.zip or
        SILVA_138_k11.fasta.sig.zip.zip, and cannot find SILVA_138_k11.fasta.sig.zip.ZIP, period.
```

so it looks to me like these are corrupted files.

They do identify as zip files:
```
% file SILVA_138_k11.fasta.sig.zip
SILVA_138_k11.fasta.sig.zip: Zip archive data, at least v2.0 to extract, compression method=store
```
so it's not that they just have the wrong name on them.

Do you have the output from generating the .zip file, a slurm log file somewhere? I'm wondering if it died with out of memory or something.

Suggest regenerating the signatures and instead of specifying a .sig file as output, specify a zip file as output.

**Comment by bryshalm** [comment]
hi @ctb 

You are right. I attempted it to generate .zip files again from sig files, close to the end of my srun and I had the same error. I was able to successfully generate .zip sig files using a batch file.

**Batch File Example**
```


#! /bin/bash
#
#SBATCH --mail-user=username@ucdavis.edu         # YOUR EMAIL ADDRESS
#SBATCH --mail-type=ALL                         # NOTIFICATIONS OF SLURM JOB STATUS - ALL, NONE, BEGIN, END, FAIL, REQUEUE
#SBATCH -J k11                           # JOB ID
#SBATCH -e k11.j%j.err                   # STANDARD ERROR FILE TO WRITE TO
#SBATCH -o k11.j%j.out                   # STANDARD OUTPUT FILE TO WRITE TO
#SBATCH -c 1                                    # NUMBER OF PROCESSORS PER TASK
#SBATCH --mem=40Gb                               # MEMORY POOL TO ALL CORES
#SBATCH --time=00-48:05:00                      # REQUESTED WALL TIME
#SBATCH -p high2                                # PARTITION TO SUBMIT TO


do sourmash sketch dna -p k=21,scaled=1 SILVA_138_SSURef_tax_silva.fasta --name-from-first --singleton -o SILVA_k11_tax.zip

done
```

I was able to generate the file `SILVA_tax_k11_new.zip` and `SILVA_tax_k21_new.zip` with the same batch file

I verified the files using `sourmash sig summarize SILVA_tax_k11_new.zip`

**Output**
```

** loading from 'SILVA_tax_k11_new.zip'
path filetype: ZipFileLinearIndex
location: /home/brymoore/sourmash_16S/silva/zipped_directory_sigs/SILVA_tax_k11_new.zip
is database? yes
has manifest? yes
num signatures: 1
** examining manifest...
total hashes: 174964
summary of sketches:
   1 sketches with DNA, k=11, scaled=1                174964 total hashes
```

Both files are currently located here: `/home/brymoore/sourmash_16S/silva/zipped_directory_sigs`

**Comment by ctb** [comment]
OK - so, I think this was a case of an incomplete file generated by an interrupted sourmash run. Thanks for following up! Closing!
