### ISSUE TITLE
sourmash gather --help raises a ValueError

### ISSUE THREAD

**Issue by bnelsj** [sourmash-bio/sourmash#3031]
When I try to get the help info for sourmash gather using the CLI, I get a ValueError. I am using sourmash 4.8.6 and python 3.11.

This issue is due to unescaped `%` characters in the usage docstring [here](https://github.com/sourmash-bio/sourmash/blob/b14ef5d0aef53b470572f5e093179273b5d37df8/src/sourmash/cli/gather.py#L42).

I can submit a pull request if that would be helpful.

Traceback:
```
sourmash gather -h

== This is sourmash version 4.8.6. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

Traceback (most recent call last):
  File "/home/bnelsj/miniforge3/envs/sourmash/bin/sourmash", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/site-packages/sourmash/__main__.py", line 11, in main
    args = sourmash.cli.parse_args(arglist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/site-packages/sourmash/cli/__init__.py", line 179, in parse_args
    return get_parser().parse_args(arglist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/site-packages/sourmash/cli/__init__.py", line 82, in parse_args
    args = super().parse_args(args=args, namespace=namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 1869, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 2096, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 2073, in consume_positionals
    take_action(action, args)
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 1978, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 1241, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 2114, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 2054, in consume_optional
    take_action(action, args, option_string)
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 1978, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 1119, in __call__
    parser.print_help()
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/site-packages/sourmash/cli/__init__.py", line 74, in print_help
    super().print_help()
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 2601, in print_help
    self._print_message(self.format_help(), file)
                        ^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 2585, in format_help
    return formatter.format_help()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 286, in format_help
    help = self._root_section.format_help()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 217, in format_help
    item_help = join([func(*args) for func, args in self.items])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 217, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
                      ^^^^^^^^^^^
  File "/home/bnelsj/miniforge3/envs/sourmash/lib/python3.11/argparse.py", line 303, in _format_usage
    usage = usage % dict(prog=self._prog)
            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
ValueError: unsupported format character '%' (0x25) at index 1546
```

**Comment by ctb** [comment]
indeed it does 😭 - thank you!
