### ISSUE TITLE
revisit InvalidDNA error?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#3104]
see https://github.com/apetkau/genomics-data-index/issues/39 (linked to https://github.com/sourmash-bio/sourmash/issues/137) which reports:

```
sourmash.exceptions.Panic: sourmash panicked: \
thread 'unnamed' panicked with 'called `Result::unwrap()` on an `Err` value: \
InvalidDNA { message: "ATTGCCGAAGTTGATGGTAACGATCCGCTCN" }' at src/core/src/signature.rs:481
```

does this still happen?

**Comment by ctb** [comment]
Not at the command line:
```
% sourmash sketch dna tests/test-data/shewanella.faa --check-sequence -f

== This is sourmash version 4.8.7. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

computing signatures for files: tests/test-data/shewanella.faa
Computing a total of 1 signature(s) for each input.
... reading sequences from tests/test-data/shewanella.faa
ERROR when reading from 'tests/test-data/shewanella.faa' - 
invalid DNA character in input k-mer: MCGIVGAVAQRDVAEILVEGLRRLEYRGYDS
```

**Comment by ctb** [comment]
and not with the Python API. The following code:

```python 
import sourmash, screed
mh = sourmash.MinHash(n=0, ksize=21, scaled=1000)

record = next(iter(screed.open('tests/test-data/shewanella.faa')))
mh.add_sequence(record.sequence)
```

yields:
```
Traceback (most recent call last):
  File "/Users/t/dev/sourmash/bad.py", line 5, in <module>
    mh.add_sequence(record.sequence)
  File "/Users/t/dev/sourmash/src/sourmash/minhash.py", line 350, in add_sequence
    self._methodcall(lib.kmerminhash_add_sequence, to_bytes(sequence), force)
  File "/Users/t/dev/sourmash/src/sourmash/utils.py", line 25, in _methodcall
    return rustcall(func, self._get_objptr(), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/t/dev/sourmash/src/sourmash/utils.py", line 78, in rustcall
    raise exc
ValueError: invalid DNA character in input k-mer: MCGIVGAVAQRDVAEILVEGL
```

🎉
