### ISSUE TITLE
enable protein sketches for pangenome hash correlations

### ISSUE THREAD

**Issue by AnneliektH** [sourmash-bio/sourmash#3201]
calc-hash-presence.py from [pangenome-hash-cor](https://github.com/ctb/2024-pangenome-hash-corr), does not yet allow me to compare protein sketches instead of nucleotide sketches. 

I'd like to compare protein-pangenomes instead of nucleotide ones

Trying in `/group/ctbrowngrp2/scratch/annie/2023-swine-sra/sourmash/pangenomics/test_virpan`

```
python ../../2024-pangenome-hash-corr/calc-hash-presence.py \
cluster1371.ranktable.csv \
cluster1371.zip \
-o cluster1371.dump \
--scaled=1

loaded 204371 hashvals... downsampling soon.
found 0 metagenomes
Traceback (most recent call last):
  File "/group/ctbrowngrp2/scratch/annie/2023-swine-sra/sourmash/pangenomics/test_virpan/sigs/../../2024-pangenome-hash-corr/calc-hash-presence.py", line 80, in <module>
    sys.exit(main())
  File "/group/ctbrowngrp2/scratch/annie/2023-swine-sra/sourmash/pangenomics/test_virpan/sigs/../../2024-pangenome-hash-corr/calc-hash-presence.py", line 37, in main
    query_minhash = next(iter(idx.signatures())).minhash.copy_and_clear()
StopIteration
```

**Comment by ctb** [comment]
just added it now - https://github.com/ctb/2024-pangenome-hash-corr/commit/7440f8ffa4288119750b3d32f8ae458cd2ad8a74

you'll need to update your `sourmash_plugin_pangenomics` first, either to the latest released version or the latest dev version.

**Comment by ctb** [comment]
(let me know if it breaks ;)

**Comment by ctb** [comment]
hmm, some more things need to be fixed before it will work. sorry!

**Comment by ctb** [comment]
ok fixed in 2024-pangenome-hash-corr https://github.com/ctb/2024-pangenome-hash-corr/commit/f2433f24828d59f1c308c3ecd711b897cf5756fd and v0.2.2 of sourmash_plugin_pangenomics, I think.

you may need to use `--protein --no-dna` with the pangenome plugin scripts. You'll also need to specify the k-mer size and scaled value far too many times. Sorry, work in progress ;).

**Comment by ctb** [comment]
did we fix this with sourmash_utils https://github.com/sourmash-bio/sourmash_utils/pull/7?
