### ISSUE TITLE
error combining SBTs

### ISSUE THREAD

**Issue by taylorreiter** [sourmash-bio/sourmash#695]
`sourmash version 2.0.1.dev1+g7e1f942`

I tried to combine the following SBTs:

```
curl -L https://osf.io/cdvqn/download -o mmetsp.tar.gz
curl -L https://osf.io/qgyax/download -o vertebrate_other.tar.gz
curl -L https://osf.io/6c9uy/download -o vertebrate_mamallian.tar.gz
curl -L https://osf.io/fnu2q/download -o protozoa.tar.gz
curl -L https://osf.io/kctus/download -o plant.tar.gz
curl -L https://osf.io/7v8ck/download -o invertebrate.tar.gz
curl -L https://osf.io/g6mcr/download -o fungi.tar.gz

tar -xzvf mmetsp.tar.gz
tar -xzvf vertebrate_other.tar.gz
tar -xzvf vertebrate_mamallian.tar.gz
tar -xzvf protozoa.tar.gz
tar -xzvf plant.tar.gz
tar -xzvf invertebrate.tar.gz
tar -xzvf fungi.tar.gz
```
Using this command:
```
sourmash sbt_combine euk_rna_k31 fungi/fungi-k31.sbt.json invertebrate/invertebrate-k31.sbt.json mmetsp-k31-named.sbt.json plant/plant-k31.sbt.json protozoa/protozoa-k31.sbt.json vertebrate_mammalian/vertebrate_mammalian-k31.sbt.json vertebrate_other/vertebrate_other-k31.sbt.json
```
And received this error:
```
== This is sourmash version 2.0.1.dev1+g7e1f942. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

combining 7 SBTs
Traceback (most recent call last):
  File "/Users/tr/miniconda3/envs/space/bin/sourmash", line 10, in <module>
    sys.exit(main())
  File "/Users/tr/miniconda3/envs/space/lib/python3.6/site-packages/sourmash/__main__.py", line 83, in main
    cmd(sys.argv[2:])
  File "/Users/tr/miniconda3/envs/space/lib/python3.6/site-packages/sourmash/commands.py", line 675, in sbt_combine
    tree.combine(new_tree)
  File "/Users/tr/miniconda3/envs/space/lib/python3.6/site-packages/sourmash/sbt.py", line 744, in combine
    smaller.nodes[0].update(n)
  File "/Users/tr/miniconda3/envs/space/lib/python3.6/site-packages/sourmash/sbt.py", line 829, in update
    parent.data.update(self.data)
  File "khmer/_oxli/graphs.pyx", line 900, in khmer._oxli.graphs.Nodegraph.update
ValueError: both nodegraphs must have same table sizes
```

any idea? @luizirber :)

**Comment by ctb** [comment]
I'm going to close this, since we've swapped out the underlying SBT implementation at least once (internal sourmash-rs now).
