### ISSUE TITLE
fix unnamed exception in rust angular_similarity method.

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#898]
`angular_similarity` on MinHash objects fails with an unnamed exception when abundances are not available. #fixme.

**Comment by ctb** [comment]
Here is some code to generate the error:

```
>>> import sourmash
>>> mh = sourmash.MinHash(n=50, ksize=3)
>>> mh.add_hash(1)
>>> mh.add_hash(2)
>>> mh.add_hash(3)
>>> mh.angular_similarity(mh)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/t/dev/sourmash/sourmash/_minhash.py", line 531, in angular_similarity
    other._get_objptr())
  File "/Users/t/dev/sourmash/sourmash/utils.py", line 25, in _methodcall
    return rustcall(func, self._get_objptr(), *args)
  File "/Users/t/dev/sourmash/sourmash/utils.py", line 78, in rustcall
    raise exc
sourmash.exceptions.Panic: sourmash panicked: thread 'unnamed' panicked with 'not implemented' at src/core/src/sketch/minhash.rs:689
```
